//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorConnect.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMentorConnect : DbContext
    {
        public DBMentorConnect()
            : base("name=DBMentorConnect")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MentorProfile> MentorProfiles { get; set; }
        public DbSet<MentorSchedule> MentorSchedules { get; set; }
        public DbSet<Mentorship> Mentorships { get; set; }
        public DbSet<StudentProfile> StudentProfiles { get; set; }
        public DbSet<StudentSchedule> StudentSchedules { get; set; }
        public DbSet<subject> subjects { get; set; }
        public DbSet<time> times { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<weekday> weekdays { get; set; }
        public DbSet<MentorResume> MentorResumes { get; set; }
        public DbSet<UserImage> UserImages { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<MentorScheduleRequest> MentorScheduleRequests { get; set; }
    }
}
