//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorResume
    {
        public int fk_mentorId { get; set; }
        public string filePath { get; set; }
    
        public virtual MentorProfile MentorProfile { get; set; }
    }
}
