//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorProfile
    {
        public MentorProfile()
        {
            this.MentorSchedules = new HashSet<MentorSchedule>();
            this.Mentorships = new HashSet<Mentorship>();
            this.MentorScheduleRequests = new HashSet<MentorScheduleRequest>();
        }
    
        public int fk_mentor_ID { get; set; }
        public string imgPath { get; set; }
        public string major { get; set; }
        public string description { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<MentorSchedule> MentorSchedules { get; set; }
        public virtual ICollection<Mentorship> Mentorships { get; set; }
        public virtual MentorResume MentorResume { get; set; }
        public virtual ICollection<MentorScheduleRequest> MentorScheduleRequests { get; set; }
    }
}
