//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProfile
    {
        public StudentProfile()
        {
            this.StudentSchedules = new HashSet<StudentSchedule>();
            this.MentorScheduleRequests = new HashSet<MentorScheduleRequest>();
        }
    
        public int fk_student_id { get; set; }
        public string imgPath { get; set; }
        public string clas { get; set; }
        public string description { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        public virtual ICollection<MentorScheduleRequest> MentorScheduleRequests { get; set; }
    }
}
