//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSchedule
    {
        public int fk_student_Id { get; set; }
        public int fk_day_Id { get; set; }
        public int fk_time_id { get; set; }
        public Nullable<int> fk_mentorship_id { get; set; }
    
        public virtual Mentorship Mentorship { get; set; }
        public virtual StudentProfile StudentProfile { get; set; }
        public virtual weekday weekday { get; set; }
        public virtual time time { get; set; }
    }
}
