//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Mentorships = new HashSet<Mentorship>();
            this.subjects = new HashSet<subject>();
        }
    
        public string UserID { get; set; }
        public string Password { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phNo { get; set; }
        public Nullable<int> user_type { get; set; }
        public int ID { get; set; }
    
        public virtual MentorProfile MentorProfile { get; set; }
        public virtual ICollection<Mentorship> Mentorships { get; set; }
        public virtual StudentProfile StudentProfile { get; set; }
        public virtual ICollection<subject> subjects { get; set; }
        public virtual UserImage UserImage { get; set; }
    }
}
