//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weekday
    {
        public weekday()
        {
            this.MentorSchedules = new HashSet<MentorSchedule>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
            this.MentorScheduleRequests = new HashSet<MentorScheduleRequest>();
        }
    
        public int dayid { get; set; }
        public string dayname { get; set; }
    
        public virtual ICollection<MentorSchedule> MentorSchedules { get; set; }
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        public virtual ICollection<MentorScheduleRequest> MentorScheduleRequests { get; set; }
    }
}
